### ISSUE TITLE
Bug: Raw Markdown links in articles instead of actual hyperlinks

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs-website#507]
In the several articles that I looked at. I'm seeing text like these ([example](https://sampleprograms.io/projects/merge-sort/)):
```
[Wikipedia’s article about Merge sort][1]
```
```
[<-- Previous Project (Maximum Subarray)](https://sampleprograms.io/projects/maximum-subarray)
[Next Project (Minimum Spanning Tree) -->](https://sampleprograms.io/projects/minimum-spanning-tree)
```

**Comment by jrg94** [comment]
This is a very strange bug. It renders correctly in GitHub: https://github.com/TheRenegadeCoder/sample-programs-website/blob/main/docs/projects/merge-sort/index.md

The source looks good too: https://raw.githubusercontent.com/TheRenegadeCoder/sample-programs-website/main/docs/projects/merge-sort/index.md

I'll have to take a peek at the HTML again.

**Comment by jrg94** [comment]
Here's the HTML as rendered:

```html
<div id="prev">

[&lt;-- Previous Project (Maximum Subarray)](https://sampleprograms.io/projects/maximum-subarray)

</div>
```

**Comment by jrg94** [comment]
It doesn't appear to be rendering correctly on any of the project pages. Very weird. I wonder when that happened.

**Comment by jrg94** [comment]
Alright, well I seem to have solved it here: https://github.com/TheRenegadeCoder/sample-programs-website/commit/f5c2b3816646a08bd00a6d607cc62a4adb4943a8

Turns out kramdown doesn't let you mix HTML and Markdown without specifying the markdown in a div. Weird, but it's fixed now. 

The other links you pointed to are actually problems with the sources. I think they'll just have to be removed at some point.
